auto: true
server: true
pygments: true
permalink: none
baseurl: "prose/"
oauth_client_id: 
gatekeeper_url: 
exclude:
- .gitignore
- README.md
- node_modules
- package.json
- Gruntfile.coffee
rootUrl: cyio/cyio.github.io
