auto: true
server: true
pygments: true
permalink: none
baseurl: "prose/"
oauth_client_id: 243028f2aacf516e33b9
gatekeeper_url: http://gatekeeper-cyio.herokuapp.com/
exclude:
- .gitignore
- README.md
- node_modules
- package.json
- Gruntfile.coffee
rootUrl: cyio/cyio.github.io
